import "@nsftx/nxg-sports-micro-frontends-example-shared/style";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://ignite-sdk.nl-ams-1.linodeobjects.com/staging/ignite-parent.js"></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
